### ISSUE TITLE
Occasional "missing favicon.ico" error from browser

### ISSUE THREAD

**Issue by dabrahams** [stlab/better-code#4]
This message shows up in Safari's web inspector from time to time when looking at slides.

[Error] Failed to load resource: the server responded with a status of 404 (Not Found) (favicon.ico, line 0)

**Comment by sean-parent** [comment]
You need to add a favicon.ico file - the browser is trying to fetch one to display in the tab. You can use the one from stlab.

**Comment by dabrahams** [comment]
Well of course that's one cure.  The question is, why does this only show up sometimes?  Not every site needs a favicon, and I can't find references to it in the code.
